#!/usr/bin/env bash

LOG_DATA=true # set to false to not log data
LOG_FILE="LOG_"$(date +%F)
ATTEMPT=0

OLD_MD5=""
NEW_MD5=""

timestamp() {
    date +"%T"
}

FILENAME="$1" && shift
echo "$FILENAME"
if [[ ! -f "$FILENAME" ]]; then
     echo "No file: $FILENAME"
     exit 1
fi
DIFF_COMMAND="cat "$FILENAME" | md5sum"

if "$LOG_DATA"; then
    touch "$LOG_FILE"
fi

while true; do
    NEW_MD5=$(eval $DIFF_COMMAND)
    if [[ "$OLD_MD5" != "$NEW_MD5" ]]; then
        OLD_MD5="$NEW_MD5"
        echo "Executing: $@"
        $@
        if [[ "$?" == '0' ]]; then
            echo "READY: $@"
        else
            echo "READY: $@"
        fi
        if "$LOG_DATA"; then
            printf "ATTEMPT $ATTEMPT\n" >> "$LOG_FILE"
            printf "$(timestamp)\n" >> "$LOG_FILE"
            printf "=========\n\n" >> "$LOG_FILE"
            cat "$FILENAME" >> "$LOG_FILE"
            printf "\n\n" >> "$LOG_FILE"
            ((++ATTEMPT))
        fi
    fi
done
