#!/usr/bin/env bash

OLD_MD5=""
NEW_MD5=""

stack build

FILENAME="$1" && shift
echo "$FILENAME"
if [[ ! -f "$FILENAME" ]]; then
     echo "No file: $FILENAME"
     exit 1
fi
DIFF_COMMAND="cat "$FILENAME" | md5sum"

while true; do
    NEW_MD5=$(eval $DIFF_COMMAND)
    if [[ "$OLD_MD5" != "$NEW_MD5" ]]; then
        OLD_MD5="$NEW_MD5"
        echo "Executing: $@"
        $@
        if [[ "$?" == '0' ]]; then
            echo "READY: $@"
        else
            echo "READY: $@"
        fi
    fi
done
