flags: {}
extra-package-dbs: []
packages:
- ./roshask
- ./roshask/msgs/Geometry_msgs/
- ./roshask/msgs/Std_msgs/
- '.'
extra-deps:
- HsOpenSSL-0.11.4.8
- data-default-generics-0.3
- non-negative-0.1.1
- numeric-prelude-0.4.2
- storable-tuple-0.0.3.2
- uri-0.1.6.4
resolver: lts-8.5
